import React from "react";
import Navbar from "./navbar";
import Link from "next/link";
import Head from "next/head";
import TodosContext from "../../contexts/TodosContext";
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Todolist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="todolist">
        <Navbar></Navbar>
        {children}
        <Link href="/todolist">
          <button>Back to todolist</button>
        </Link>
      </div>
    </>
  );
};

export default Layout;
