import Head from "next/head";

import Navbar from "../../components/todolist/navbar";
import Layout from "../../components/todolist/Layout";

export default function Home() {
  return (
    <Layout>
      <div className="container">
        <Head>
          <title>Todolist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="main"></main>

        <footer className="footer"></footer>
      </div>
    </Layout>
  );
}
